---
tags: []
layout: input_bottom
editor: code
type: interactive
extra_visible: false
manual_evaluation: false
choices: []
goal:
  kind: query_outputs
  query: git status
  output: |-
    On branch master
    nothing to commit, working directory clean
