---
tags: []
layout: input_bottom
editor: code
type: interactive
extra_visible: false
manual_evaluation: false
choices: []
goal:
  kind: last_query_outputs
  output: |
    On branch master

    Initial commit

    Changes to be committed:
    (use "git rm --cached <file>..." to unstage)

    new file: capitulo1.txt
