---
tags: []
layout: input_bottom
editor: code
type: interactive
extra_visible: false
manual_evaluation: false
choices: []
goal:
  kind: query_outputs
  query: git status
  output: "On branch master\n\nInitial commit\n\nChanges to be committed:\n  (use
    \"git rm --cached <file>...\" to unstage)\n\n\tnew file:   capitulo1.txt\n\n"
